### PR TITLE
Added cart without Auth

### PR DESCRIPTION
**Pull request by bhavyaj12**
### Cart Page with functionality in all pages

- I have added the cart component using useContext and useReducer
- I have modified the product, wishlist component to enable cart functionality
- Full Cart page with functional button 
- Price calculated on cart page
- Increase, decrease quantity feature on cart page
- Also added scroll to function for products, and floating button on all pages

### Files to check

- [ ] src/components/cart-items/CartCard.jsx
- [ ] src/components/cart-items/CartPrice.jsx
- [ ] src/components/navigation-top/NavigationTop.jsx
- [ ] src/components/product-card/ProductCard.jsx
- [ ] src/components/wishlist-card/WishlistCard.jsx
- [ ] src/contexts/cart-context.js
- [ ] src/pages/cart-page/CartPage.jsx
- [ ] src/reducers/cart-reducer.js

Ignore other files, they're index, styles

### What not to check

- Authentication

image

### CODE REVIEW

**Review by harshitpaliwal95 — APPROVED** [review]
- clean ui and readable code

### suggestion
- add top scroll on cart page

**Review by Balakumar3018 — APPROVED** [review]
Looks good to me.

**Review by Pratham82 — APPROVED** [review]
- All functionality is working, good code structure
- Some UI suggestions:
- The images which do not have transparent backgrounds, will look good with rounded corners
- Also the fonts of the tag is bigger it will be better for visibility
image

Apart from this site looks good and theme suits the products

**Comment by bhavyaj12** [comment]
> 

Thanks, will note and work on these suggestions!

**Pull request merged**
